# Generated by Django 4.2.7 on 2023-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deliverables",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="milestones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
