# Generated by Django 4.2.7 on 2023-12-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_remove_document_project"),
        ("projects", "0002_project_deliverables_project_milestones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="related_projects", to="documents.document"
            ),
        ),
    ]
