# Generated by Django 4.2.7 on 2023-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="activity_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="device_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
