# Generated by Django 4.2.7 on 2023-12-24 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="access_level",
            field=models.CharField(
                choices=[("read", "Read"), ("write", "Write"), ("edit", "Edit")],
                default="read",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
