# Generated by Django 4.2.7 on 2023-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("alert", "Alert"),
                    ("reminder", "Reminder"),
                    ("update", "Update"),
                ],
                default="update",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="preference",
            field=models.CharField(
                choices=[("email", "Email"), ("app", "App"), ("sms", "SMS")],
                default="app",
                max_length=100,
            ),
        ),
    ]
