name: AlignWork Backend CI/CD Pipeline (Staging)

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image for Staging
      if: github.ref == 'refs/heads/staging'
      run: |  
        docker build -t alw:staging .
        docker tag alw:staging ${{ secrets.DOCKER_HUB_USERNAME }}/staging/alw:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/staging/alw:latest

    - name: Deploy to Staging Server
      if: github.ref == 'refs/heads/staging'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/staging/alw:latest
          docker stop alw-staging || true
          docker rm alw-staging || true
          docker run --name alw-staging -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/staging/alw:latest